<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeleteIcon(Contact)</name>
   <tag></tag>
   <elementGuidId>17a8471c-83b5-4352-8192-8fc220008c0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-icon.img-icon-s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b14-l3_0-242_0-b20-Column2']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-icon img-icon-s</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/FusionCenter/img/Common_LIB.Delete.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b14-l3_0-242_0-b20-Column2&quot;)/div[1]/a[1]/img[@class=&quot;img-icon img-icon-s&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b14-l3_0-242_0-b20-Column2']/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
