<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profile_Dropdown</name>
   <tag></tag>
   <elementGuidId>b56e1d0c-c705-4bcd-9d96-93f0833fd39d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submenu-icon.fa.submenu-arrow.fa-2x</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-b3-b2-SubMenuHeader']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submenu-icon fa submenu-arrow fa-2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-b3-b2-SubMenuHeader&quot;)/div[@class=&quot;submenu-icon fa submenu-arrow fa-2x&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-b3-b2-SubMenuHeader']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
