<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimeZone</name>
   <tag></tag>
   <elementGuidId>87b61367-d535-49b0-886d-88c4a351c43b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b12-b8-b13-TimeZones</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b12-b8-b13-TimeZones']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-display form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b12-b8-b13-TimeZones</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectNiue TimeSamoa Standard TimeSamoa Standard TimeCook Islands Standard TimeHawaii-Aleutian Standard TimeHawaii-Aleutian Standard TimeTahiti TimeMarquesas TimeAlaska Standard TimeAlaska Standard TimeAlaska Standard TimeAlaska Standard TimeAlaska Standard TimeAlaska Standard TimeGambier TimePacific Standard TimePacific Standard TimePacific Standard TimePitcairn TimeMexican Pacific Standard TimeMexican Pacific Standard TimeMexican Pacific Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimeMountain Standard TimePacific Standard TimePacific Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeCentral Standard TimeEaster Island Standard TimeGalapagos TimeAcre Standard TimeAcre Standard TimeColombia Standard TimeCuba Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEastern Standard TimeEcuador TimePeru Standard TimeAmazon Standard TimeAmazon Standard TimeAmazon Standard TimeAmazon Standard TimeAmazon Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeAtlantic Standard TimeBolivia TimeChile Standard TimeGuyana TimeParaguay Standard TimeVenezuela TimeNewfoundland Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeArgentina Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeBrasilia Standard TimeFalkland Islands Standard TimeFrench Guiana TimeGMTGMT-03:00GMT-03:00Rothera TimeSt. Pierre &amp; Miquelon Standard TimeSuriname TimeUruguay Standard TimeWestern Argentina Standard TimeFernando de Noronha Standard TimeSouth Georgia TimeAzores Standard TimeCape Verde Standard TimeEast Greenland Standard TimeCoordinated Universal TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeGreenwich Mean TimeWest Africa Standard TimeWestern European Standard TimeWestern European Standard TimeWestern European Standard TimeWestern European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeCentral European Standard TimeGreenwich Mean TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWest Africa Standard TimeWestern European Standard TimeWestern European Standard TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeCentral Africa TimeEast Africa TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeEastern European Standard TimeGMT+02:00Israel Standard TimeSouth Africa Standard TimeSouth Africa Standard TimeSouth Africa Standard TimeArabian Standard TimeArabian Standard TimeArabian Standard TimeArabian Standard TimeArabian Standard TimeArabian Standard TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeEast Africa TimeGMT+03:00GMT+03:00Moscow Standard TimeMoscow Standard TimeMoscow Standard TimeMoscow Standard TimeSyowa TimeIran Standard TimeArmenia Standard TimeAzerbaijan Standard TimeGMT+04:00GMT+04:00GMT+04:00Georgia Standard TimeGulf Standard TimeGulf Standard TimeMauritius Standard TimeRÃ©union TimeSamara Standard TimeSeychelles TimeAfghanistan TimeEast Kazakhstan TimeFrench Southern &amp; Antarctic TimeMaldives TimeMawson TimePakistan Standard TimeTajikistan TimeTurkmenistan Standard TimeUzbekistan Standard TimeUzbekistan Standard TimeWest Kazakhstan TimeWest Kazakhstan TimeWest Kazakhstan TimeWest Kazakhstan TimeYekaterinburg Standard TimeIndia Standard TimeIndia Standard TimeNepal TimeBangladesh Standard TimeBhutan TimeEast Kazakhstan TimeGMTGMT+06:00Indian Ocean TimeKyrgyzstan TimeOmsk Standard TimeVostok TimeCocos Islands TimeMyanmar TimeChristmas Island TimeDavis TimeGMT+07:00GMT+07:00Hovd Standard TimeIndochina TimeIndochina TimeIndochina TimeIndochina TimeKrasnoyarsk Standard TimeKrasnoyarsk Standard TimeNovosibirsk Standard TimeWestern Indonesia TimeWestern Indonesia TimeAustralian Western Standard TimeBrunei Darussalam TimeCentral Indonesia TimeChina Standard TimeChina Standard TimeChoibalsan Standard TimeHong Kong Standard TimeIrkutsk Standard TimeMalaysia TimeMalaysia TimePhilippine Standard TimeSingapore Standard TimeTaipei Standard TimeUlaanbaatar Standard TimeAustralian Central Western Standard TimeEast Timor TimeEastern Indonesia TimeJapan Standard TimeKorean Standard TimeKorean Standard TimePalau TimeYakutsk Standard TimeYakutsk Standard TimeYakutsk Standard TimeAustralian Central Standard TimeAustralian Central Standard TimeAustralian Central Standard TimeAustralian Eastern Standard TimeAustralian Eastern Standard TimeAustralian Eastern Standard TimeAustralian Eastern Standard TimeAustralian Eastern Standard TimeChamorro Standard TimeChamorro Standard TimeChuuk TimeDumont-dâUrville TimeMacquarie Island TimePapua New Guinea TimeVladivostok Standard TimeVladivostok Standard TimeLord Howe Standard TimeAustralian Western Standard TimeGMT+11:00GMT+11:00Kosrae TimeMagadan Standard TimeNew Caledonia Standard TimeNorfolk Island TimePonape TimeSakhalin Standard TimeSolomon Islands TimeVanuatu Standard TimeAnadyr Standard TimeFiji Standard TimeGilbert Islands TimeMarshall Islands TimeMarshall Islands TimeNauru TimeNew Zealand Standard TimeNew Zealand Standard TimePetropavlovsk-Kamchatski Standard TimeTuvalu TimeWake Island TimeWallis &amp; Futuna TimeChatham Standard TimeApia Standard TimePhoenix Islands TimeTokelau TimeTonga Standard TimeLine Islands Time</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b12-b8-b13-TimeZones&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b12-b8-b13-TimeZones']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b12-b8-b13-TimeZones-container']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
