<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Eye_Icon</name>
   <tag></tag>
   <elementGuidId>9093dcba-4d4e-4d32-bf30-aa4263c667c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='LoginForm']/div/div[2]/div[2]/a/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-eye-slash.fa-2x</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-eye-slash fa-2x</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LoginForm&quot;)/div[@class=&quot;login-inputs margin-top-base font-size-xs font-bold&quot;]/div[@class=&quot;margin-top-base password-contianer&quot;]/div[@class=&quot;password-field-icon-container&quot;]/a[@class=&quot;OSFillParent&quot;]/div[@class=&quot;margin-top-s&quot;]/i[@class=&quot;icon fa fa-eye-slash fa-2x&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='LoginForm']/div/div[2]/div[2]/a/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
   </webElementXpaths>
</WebElementEntity>
