<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit(Product)</name>
   <tag></tag>
   <elementGuidId>74d05f17-92be-42ec-891b-727a90f1bfc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-align-center > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b18-l2_0-452_0-b19-Column1']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/FusionCenter/img/Common_LIB.Pencil.svg?r8b2ORsIcWH0Lj9V48JVHQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b18-l2_0-452_0-b19-Column1&quot;)/div[@class=&quot;text-align-center&quot;]/a[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b18-l2_0-452_0-b19-Column1']/div/a/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a/img</value>
   </webElementXpaths>
</WebElementEntity>
