<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClientsDashboard</name>
   <tag></tag>
   <elementGuidId>6f234763-9501-4163-a622-de69d1023ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.order-summary-datatable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='GridContainer']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>order-summary-datatable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ActionClient NameStatusAddressCountryStateCityZip CodeSales RepAccount ManagerCreated OnLast Updated OnLast Updated ByTest Client 123ActiveSmoke Tester12/10/2021, 6:31 PM12/16/2021, 5:52 PMadminClient TesterActiveAdminUserJoey Castillo12/10/2021, 6:28 PMSmoke 1InactiveLine 1, Line 2United StatesAlabamaAlexander35010AdminUserAnon User12/01/2021, 1:44 PM12/01/2021, 1:54 PMadminTest AmericaActiveAdminUserAdminUser12/01/2021, 12:55 PM12/01/2021, 12:55 PM</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GridContainer&quot;)/div[@class=&quot;order-summary-datatable&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GridContainer']/div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clients List'])[1]/following::div[15]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]</value>
   </webElementXpaths>
</WebElementEntity>
