<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CarriersDashboard</name>
   <tag></tag>
   <elementGuidId>61a865b4-69e3-44a7-8bea-d8ac29a09848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b16-List</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b16-List']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b16-List</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Client - Carrier Association ListDownloadActionsCarrier SCAC CodeCarrier NameSite CodeSite NameContract Effective DateContract Expiration DatePricingAudit PreferenceClient BOLBrokerCurrencyDefault RuleARFWAMERICAN FREIGHTWAYSTestSiteSiteforAutomation12/25/2021GeneralManualYesYesUSDsaSA sfdsa fsafdasfsfa sdjsjasoiPJ jiodsaJS OIDJSIOASjdsioaJDIOSAJ jidsoaj ioadIOJAS jidsodas JDASIO jopdjs jiaOPODJ iodaPdj iodasPJDiosaJ IDOASDJ IOSD DJIOASD saNDwqn edn,mads dk;aALLVALLIED VAN LINESTestSiteSiteforAutomation12/21/202101/20/2023NexterusManualYesYesUSD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b16-List&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b16-List']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='$b16']/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Association'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[2]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/div/div/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
